import { Box, Button, Flex, Text, useColorMode } from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import DeviceControlSection from "../components/deviceControl";
import Header from "../components/header";
import ColorModeToggle from "../components/themeToggle";

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <Box>
      <Head>
        <title>NFT Gated IoT Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <DeviceControlSection />
    </Box>
  );
};

export default Home;
